# Generated by Django 4.2.6 on 2023-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('no_of_seats', models.PositiveIntegerField()),
                ('price_for_eachday', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
