# Generated by Django 4.2.6 on 2023-11-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenumber', models.CharField(max_length=10)),
                ('no_of_days', models.IntegerField()),
                ('date_of_booking', models.DateTimeField(auto_now_add=True)),
                ('name_of_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vehicle')),
            ],
        ),
    ]
