# Generated by Django 4.2.6 on 2023-11-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('name_on_card', models.CharField(max_length=100)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
