# Generated by Django 4.2.6 on 2023-11-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_to_pay',
        ),
    ]
